export enum AcquiringEntity{
  GIACT = 74,
  MATCH = 75,
  AMEX = 76,
  G2 = 77,
  TINCHECK = 78,
  EXPERIAN = 113,
  WEBSHIELD = 117,
  TRULIOO = 118,
  TSYSBOARDING = 125,
  WORLDCHECK = 126,
  NUVEIUS = 87,
  NUVEICANADA = 116,
  TANGO = 132,
  DIGITALPAYMENTGW = 133,
  TSYSCOMMADUPDATEMERCHANT = "TSCSM",
  TSYSCOMMADUPDATETERMINAL = "TSAUM",
  TSYSCOMMADADDTERMINAL = "TSAU",
  TSYSCOMMADVIEWMERCHANT = "TSCSV",
  TSYSCOMMADVIEWTERMINAL = "TSAUV"

}
