import * as Yup from 'yup';

// export const merchantValidationSchema = Yup.object().shape({
//     GeneralInformation: Yup.object().shape({
//         agentId: Yup.string().label('agentId'),
//         agentFirstName: Yup.string().label('agentFirstName'),
//         agentLastName: Yup.string().label('agentLastName'),
//         agentEmail: Yup.string().label('agentEmail'),
//         profileDetailId: Yup.string().label('profileDetailId'),
//         dba: Yup.object().shape({
//             name: Yup.string().label('name'),
//             address: Yup.object().shape({
//                 profileDetailId: Yup.string().label('profileDetailId'),
//                 profileContactId: Yup.string().label('profileContactId'),
//                 addressLine1: Yup.string().label('addressLine1'),
//                 addressLine2: Yup.string().label('addressLine2'),
//                 city: Yup.string().label('city'),
//                 stateId: Yup.string().label('stateId'),
//                 zipCode: Yup.string().label('zipCode'),
//                 homePhone: Yup.string().label('homePhone'),
//                 countryId: Yup.string().label('countryId'),
//                 faxNumber: Yup.string().label('faxNumber'),
//                 unitDesignator: Yup.string().label('unitDesignator'),
//                 unitDesignatorDetail: Yup.string().label('unitDesignatorDetail'),
//             }),
//         }),
//         legal: Yup.object().shape({
//             name: Yup.string().label('name'),
//             address: Yup.object().shape({
//                 profileDetailId: Yup.string().label('profileDetailId'),
//                 profileContactId: Yup.string().label('profileContactId'),
//                 addressLine1: Yup.string().label('addressLine1'),
//                 addressLine2: Yup.string().label('addressLine2'),
//                 city: Yup.string().label('city'),
//                 stateId: Yup.string().label('stateId'),
//                 zipCode: Yup.string().label('zipCode'),
//                 homePhone: Yup.string().label('homePhone'),
//                 countryId: Yup.string().label('countryId'),
//                 faxNumber: Yup.string().label('faxNumber'),
//                 unitDesignator: Yup.string().label('unitDesignator'),
//                 unitDesignatorDetail: Yup.string().label('unitDesignatorDetail'),
//             }),
//         }),
//     }),
//     OwnerInformation: Yup.string().label('OwnerInformation'),
//     SectionId: Yup.string().label('SectionId'),
//     Id: Yup.string().label('Id'),
//     status: Yup.string().label(status)
// })

export let MerchantObject = new Object({
    sectionId: null,
    id: null,
    status: null,
    businessInformation : new Object({
        agentId : null,
        agentFirstName : null,
        agentLastName: null,
        agentEmail: null,
        profileDetailId : null,
        profileContactId : null,
        dba : new Object({
            name : null,
            address : new Object({
                profileDetailId: null,
                profileContactId: null,
                addressLine1: null,
                addressLine2: null,
                city: null,
                stateId: null,
                zipCode: null,
                homePhone: null,
                countryId: null,
                faxNumber: null,
                unitDesignator: null,
                unitDesignatorDetail: null
            })
        }),
        legal : new Object({
            name : null,
            address : new Object({
                profileDetailId: null,
                profileContactId: null,
                addressLine1: null,
                addressLine2: null,
                city: null,
                stateId: null,
                zipCode: null,
                homePhone: null,
                countryId: null,
                faxNumber: null,
                unitDesignator: null,
                unitDesignatorDetail: null
            })
        }),
        merchantTypeId: null,
        contactName: null,
        contactEmail: null,
        contactCellPhone: null,
        fedTaxId: null,
        website: null,
        ownershipTypeId: null,
        businessOpenDate: null,
        businessDescription: null,
        refundPolicy: null,
        siteSurvey: null,
        processingInfo : new Object({
            yearsInBusiness: null,
            averageTicket: null,
            highTicket: null,
            monthlyVolume: null,
            motoPercentage: null,
            internetPercentage: null,
            cardsAcceptDetails: null,
            amexNumber: null,
            currency_code: null,
            language_code: null,
            seller_id: null,
            jcb_indicator: null,
            amex_boarding_status: null,
            amex_boarding_date: null,
            dinersNumber: null,
            annualVolume: null,
            refundWithinDays: null,
            requirePreAuthorizationCapabilities: null,
            annualCreditCardVolume: null,
            maxRefundAmount: null,
            noOfRefundPerMonth: null,
            cardSwipedPercent: null,
            provideCashoutServices: null,
            requireTippingFunctionality: null,
            weeklySubscriptionPercent: null,
            monthlySubscriptionPercent: null,
            annuallySubscriptionPercent: null,
            biAnnuallySubscriptionPercent: null,
            otherSubscriptionPercent: null,
            termsOfSubscription: null,
            salesValueDepositAmount: null,
            deliveryDaysFromDateofDeposit: null,
            deliveredGoodsTimeofPayment: null,
            amexMonthlyNetworkVol: null,
            amexavgTicketamount: null,
            amexhighticketAmount: null,
            isCurrentlyAcceptingAmex: null
        }),
        tradeReferences : null,
        questionnaire : new Object({
            cardsCharged: null,
            cardsChargedDetail: null,
            productDeliveredImmediately: null,
            productDeliveredSevenDays: null,
            productDeliveredFourteenDays: null,
            productDeliveredThirtyDays: null,
            productDeliveredOverThirtyDays: null
        }),
        compliance : new Object({
            thirdPartypaymentapplicationname: null,
            thirdPartypaymentapplicationversion: null,
            paymentSSL: null
        }),
        otherAddress: new Object({
            profileDetailId: null,
            profileContactId: null,
            addressLine1: null,
            city: null,
            stateId: null,
            zipCode: null,
            countryId: null
        }),
        mcc_code_id: null,
        currentlyAcceptingPayments: null,
        processingHistoryAttachments: null,
        currenyAccept: null,
        ancillaryServices: null,
        fraudReductionServices: null,
        currentlyFraudReductionServices: null,
        accountTerminated: null,
        accountTerminatedMatched: null,
        amexyearsbusiness: null,
        iRSTaxName: null,
        businessTypeBeingSold: null,
        deliveryTime: null,
        amexCommunications: null,
        miscellaneousnotes: null,
        serviceSold: null,
        IsSameAddress: null,
        inventory: null,
        MerchantSignedDate: null,
        agent_contact_name: null,
        agent_contact_email: null,
        direct_debit_merchant_fee: null,
        isDinerFunding: null,
        isAmexFunding: null,
        isProperLicenseVisible: null,
        businessLine: null,
        operationalImContact: null,
        businessImContact: null,
        previousProcessor: null,
        namePreviousProcessor: null,
        subjectRiskProgram: null,
        detailSubjectRiskProgram: null,
        dateSubjectRiskProgram: null,
        dynamicCurrencyConversion: null,
        SpecialProgramme: null,
        PartnerId: null,
        SponsorBank: null,
        thirdPartyPaymentApplication: null,
        merchantServicing: null,
        cardAcceptancy: null,
        daysSuspend: null
    }),
    owners: [{
        profileDetailId: null,
        profileContactId: null,
        firstName: null,
        titleId: null,
        ownershipFrom: null,
        dob: null,
        address: {
            addressLine1: null,
            addressLine2: null,
            city: null,
            stateId: null,
            zipCode: null,
            homePhone: null,
            countryId: null,
            email: null,
            faxNumber: null,
            citizenship: null
        },
        identifications: [],
        benificiaryOwner: null
    }]
})


export type MerchantDetails = {
    sectionId : null,
    id : null,
    businessInformation : businessInformation,
    
}

// business information section starts
export type businessInformation = {
    agentId : null,
    agentFirstName : any,
    agentLastName : any,
    agentEmail : any,
    profileDetailId : any,
    profileContactId : any,
    dba : dba,
    legal : legal,
    merchantTypeId: any,
    contactName: any,
    contactEmail: any,
    website: any,
    ownershipTypeId: any,
    businessOpenDate: any,
    businessDescription: any,
    refundPolicy: any,
    siteSurvey: any,
    processingInfo : processingInfo,
    tradeReferences : any,
    questionnaire : questionnaire,
    compliance : compliance,
    mcc_code_id: any,
    currentlyAcceptingPayments: any,
    processingHistoryAttachments: any,
    currenyAccept: any,
    ancillaryServices: any,
    fraudReductionServices: any,
    currentlyFraudReductionServices: any,
    accountTerminated: any,
    accountTerminatedMatched: any,
    amexyearsbusiness: null,
    iRSTaxName: any,
    businessTypeBeingSold: any,
    deliveryTime: any,
    amexCommunications: any,
    miscellaneousnotes: any,
    serviceSold: any,
    IsSameAddress: any,
    inventory: any,
    MerchantSignedDate: any,
    agent_contact_name: any,
    agent_contact_email: any,
    direct_debit_merchant_fee: null,
    isDinerFunding: null,
    isAmexFunding: null,
    isProperLicenseVisible: null,
    businessLine: any,
    operationalImContact: any,
    businessImContact: any,
    previousProcessor: any,
    namePreviousProcessor: any,
    subjectRiskProgram: any,
    detailSubjectRiskProgram: any,
    dateSubjectRiskProgram: any,
    dynamicCurrencyConversion: any,
    SpecialProgramme: any,
    PartnerId: any,
    SponsorBank: any,
    thirdPartyPaymentApplication: any,
    merchantServicing: any,
    cardAcceptancy: any,
    daysSuspend: any
}
export type dba = {
    name : any,
    address : address
}
export type legal = {
    name : any,
    address : address
}
export type address = {
    profileDetailId: any,
    profileContactId: any,
    addressLine1: any,
    addressLine2: any,
    city: any,
    stateId: any,
    zipCode: any,
    homePhone: any,
    countryId: any,
    faxNumber: any,
    unitDesignator: any,
    unitDesignatorDetail: any
}
export type processingInfo = {
    yearsInBusiness: any,
    averageTicket: any,
    highTicket: any,
    monthlyVolume: any,
    motoPercentage: any,
    internetPercentage: any,
    cardsAcceptDetails: any,
    amexNumber: any,
    currency_code: any,
    language_code: any,
    seller_id: any,
    jcb_indicator: any,
    amex_boarding_status: any,
    amex_boarding_date: any,
    dinersNumber: any,
    annualVolume: any,
    refundWithinDays: any,
    requirePreAuthorizationCapabilities: any,
    annualCreditCardVolume: any,
    maxRefundAmount: any,
    noOfRefundPerMonth: any,
    cardSwipedPercent: any,
    provideCashoutServices: any,
    requireTippingFunctionality: any,
    weeklySubscriptionPercent: any,
    monthlySubscriptionPercent: any,
    annuallySubscriptionPercent: any,
    biAnnuallySubscriptionPercent: any,
    otherSubscriptionPercent: any,
    termsOfSubscription: any,
    salesValueDepositAmount: any,
    deliveryDaysFromDateofDeposit: any,
    deliveredGoodsTimeofPayment: any,
    amexMonthlyNetworkVol: any,
    amexavgTicketamount: any,
    amexhighticketAmount: any,
    isCurrentlyAcceptingAmex: any
}
export type questionnaire = {
    cardsCharged: any,
    cardsChargedDetail: any,
    productDeliveredImmediately: any,
    productDeliveredSevenDays: any,
    productDeliveredFourteenDays: any,
    productDeliveredThirtyDays: any,
    productDeliveredOverThirtyDays: any
}
export type compliance = {
    thirdPartypaymentapplicationname: any,
    thirdPartypaymentapplicationversion: any,
    paymentSSL: any
}

// business information section ends

// const merchantValidationSchema = Yup.object().shape({
//     email: Yup.string()
//       .label('Email')
//       .email('Enter a valid email')
//       .required('Please enter a registered email'),
//     password: Yup.string()
//       .label('Password')
//       .required()
//       .min(4, 'Password must have at least 4 characters ')
// })